//------------------------------------------------------------------------------
// <auto-generated>
//     Este código lo genera una herramienta.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Monolito.Dashboard
{
    public partial class MiCarrito
    {
        protected global::System.Web.UI.ScriptManager ScriptManager1;
        protected global::System.Web.UI.UpdatePanel upCarrito;
        protected global::System.Web.UI.WebControls.Label lblTotalItems;
        protected global::System.Web.UI.WebControls.Label lblTotalPrecio;
        protected global::System.Web.UI.WebControls.Repeater rptCarrito;
        protected global::System.Web.UI.WebControls.Panel pnlVacio;
        protected global::System.Web.UI.WebControls.Panel pnlToast;
        protected global::System.Web.UI.WebControls.Label lblToast;
        protected global::System.Web.UI.WebControls.LinkButton btnLogout;
    }
}
