#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Capa_Datos
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="Monolito4to")]
	public partial class DataClasses1DataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Definiciones de métodos de extensibilidad
    partial void OnCreated();
    partial void Inserttbl_carrito(tbl_carrito instance);
    partial void Updatetbl_carrito(tbl_carrito instance);
    partial void Deletetbl_carrito(tbl_carrito instance);
    partial void Inserttbl_categoria(tbl_categoria instance);
    partial void Updatetbl_categoria(tbl_categoria instance);
    partial void Deletetbl_categoria(tbl_categoria instance);
    partial void Inserttbl_producto(tbl_producto instance);
    partial void Updatetbl_producto(tbl_producto instance);
    partial void Deletetbl_producto(tbl_producto instance);
    partial void Inserttbl_producto_fotos(tbl_producto_fotos instance);
    partial void Updatetbl_producto_fotos(tbl_producto_fotos instance);
    partial void Deletetbl_producto_fotos(tbl_producto_fotos instance);
    partial void Inserttbl_proveedor(tbl_proveedor instance);
    partial void Updatetbl_proveedor(tbl_proveedor instance);
    partial void Deletetbl_proveedor(tbl_proveedor instance);
    partial void Inserttbl_tipo_usuario(tbl_tipo_usuario instance);
    partial void Updatetbl_tipo_usuario(tbl_tipo_usuario instance);
    partial void Deletetbl_tipo_usuario(tbl_tipo_usuario instance);
    partial void Inserttbl_usuario(tbl_usuario instance);
    partial void Updatetbl_usuario(tbl_usuario instance);
    partial void Deletetbl_usuario(tbl_usuario instance);
    partial void Inserttbl_usuario_fotos(tbl_usuario_fotos instance);
    partial void Updatetbl_usuario_fotos(tbl_usuario_fotos instance);
    partial void Deletetbl_usuario_fotos(tbl_usuario_fotos instance);
    #endregion
		
		public DataClasses1DataContext() : 
				base(global::Capa_Datos.Properties.Settings.Default.Monolito4toConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<tbl_carrito> tbl_carrito
		{
			get
			{
				return this.GetTable<tbl_carrito>();
			}
		}
		
		public System.Data.Linq.Table<tbl_categoria> tbl_categoria
		{
			get
			{
				return this.GetTable<tbl_categoria>();
			}
		}
		
		public System.Data.Linq.Table<tbl_producto> tbl_producto
		{
			get
			{
				return this.GetTable<tbl_producto>();
			}
		}
		
		public System.Data.Linq.Table<tbl_producto_fotos> tbl_producto_fotos
		{
			get
			{
				return this.GetTable<tbl_producto_fotos>();
			}
		}
		
		public System.Data.Linq.Table<tbl_proveedor> tbl_proveedor
		{
			get
			{
				return this.GetTable<tbl_proveedor>();
			}
		}
		
		public System.Data.Linq.Table<tbl_tipo_usuario> tbl_tipo_usuario
		{
			get
			{
				return this.GetTable<tbl_tipo_usuario>();
			}
		}
		
		public System.Data.Linq.Table<tbl_usuario> tbl_usuario
		{
			get
			{
				return this.GetTable<tbl_usuario>();
			}
		}
		
		public System.Data.Linq.Table<tbl_usuario_fotos> tbl_usuario_fotos
		{
			get
			{
				return this.GetTable<tbl_usuario_fotos>();
			}
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.desencriptacon", IsComposable=true)]
		public string desencriptacon([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarBinary(MAX)")] System.Data.Linq.Binary clave)
		{
			return ((string)(this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), clave).ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.encriptacon", IsComposable=true)]
		public System.Data.Linq.Binary encriptacon([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(50)")] string clave)
		{
			return ((System.Data.Linq.Binary)(this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), clave).ReturnValue));
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tbl_carrito")]
	public partial class tbl_carrito : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _car_id;
		
		private int _usu_id;
		
		private int _pro_id;
		
		private System.Nullable<System.DateTime> _car_fecha;
		
		private EntityRef<tbl_producto> _tbl_producto;
		
		private EntityRef<tbl_usuario> _tbl_usuario;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Oncar_idChanging(int value);
    partial void Oncar_idChanged();
    partial void Onusu_idChanging(int value);
    partial void Onusu_idChanged();
    partial void Onpro_idChanging(int value);
    partial void Onpro_idChanged();
    partial void Oncar_fechaChanging(System.Nullable<System.DateTime> value);
    partial void Oncar_fechaChanged();
    #endregion
		
		public tbl_carrito()
		{
			this._tbl_producto = default(EntityRef<tbl_producto>);
			this._tbl_usuario = default(EntityRef<tbl_usuario>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_car_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int car_id
		{
			get
			{
				return this._car_id;
			}
			set
			{
				if ((this._car_id != value))
				{
					this.Oncar_idChanging(value);
					this.SendPropertyChanging();
					this._car_id = value;
					this.SendPropertyChanged("car_id");
					this.Oncar_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_usu_id", DbType="Int NOT NULL")]
		public int usu_id
		{
			get
			{
				return this._usu_id;
			}
			set
			{
				if ((this._usu_id != value))
				{
					if (this._tbl_usuario.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onusu_idChanging(value);
					this.SendPropertyChanging();
					this._usu_id = value;
					this.SendPropertyChanged("usu_id");
					this.Onusu_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_pro_id", DbType="Int NOT NULL")]
		public int pro_id
		{
			get
			{
				return this._pro_id;
			}
			set
			{
				if ((this._pro_id != value))
				{
					if (this._tbl_producto.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onpro_idChanging(value);
					this.SendPropertyChanging();
					this._pro_id = value;
					this.SendPropertyChanged("pro_id");
					this.Onpro_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_car_fecha", DbType="DateTime")]
		public System.Nullable<System.DateTime> car_fecha
		{
			get
			{
				return this._car_fecha;
			}
			set
			{
				if ((this._car_fecha != value))
				{
					this.Oncar_fechaChanging(value);
					this.SendPropertyChanging();
					this._car_fecha = value;
					this.SendPropertyChanged("car_fecha");
					this.Oncar_fechaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tbl_producto_tbl_carrito", Storage="_tbl_producto", ThisKey="pro_id", OtherKey="pro_id", IsForeignKey=true)]
		public tbl_producto tbl_producto
		{
			get
			{
				return this._tbl_producto.Entity;
			}
			set
			{
				tbl_producto previousValue = this._tbl_producto.Entity;
				if (((previousValue != value) 
							|| (this._tbl_producto.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._tbl_producto.Entity = null;
						previousValue.tbl_carrito.Remove(this);
					}
					this._tbl_producto.Entity = value;
					if ((value != null))
					{
						value.tbl_carrito.Add(this);
						this._pro_id = value.pro_id;
					}
					else
					{
						this._pro_id = default(int);
					}
					this.SendPropertyChanged("tbl_producto");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tbl_usuario_tbl_carrito", Storage="_tbl_usuario", ThisKey="usu_id", OtherKey="usu_id", IsForeignKey=true)]
		public tbl_usuario tbl_usuario
		{
			get
			{
				return this._tbl_usuario.Entity;
			}
			set
			{
				tbl_usuario previousValue = this._tbl_usuario.Entity;
				if (((previousValue != value) 
							|| (this._tbl_usuario.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._tbl_usuario.Entity = null;
						previousValue.tbl_carrito.Remove(this);
					}
					this._tbl_usuario.Entity = value;
					if ((value != null))
					{
						value.tbl_carrito.Add(this);
						this._usu_id = value.usu_id;
					}
					else
					{
						this._usu_id = default(int);
					}
					this.SendPropertyChanged("tbl_usuario");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tbl_categoria")]
	public partial class tbl_categoria : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _cat_id;
		
		private string _cat_nombre;
		
		private System.Nullable<char> _cat_estado;
		
		private EntitySet<tbl_producto> _tbl_producto;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Oncat_idChanging(int value);
    partial void Oncat_idChanged();
    partial void Oncat_nombreChanging(string value);
    partial void Oncat_nombreChanged();
    partial void Oncat_estadoChanging(System.Nullable<char> value);
    partial void Oncat_estadoChanged();
    #endregion
		
		public tbl_categoria()
		{
			this._tbl_producto = new EntitySet<tbl_producto>(new Action<tbl_producto>(this.attach_tbl_producto), new Action<tbl_producto>(this.detach_tbl_producto));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cat_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int cat_id
		{
			get
			{
				return this._cat_id;
			}
			set
			{
				if ((this._cat_id != value))
				{
					this.Oncat_idChanging(value);
					this.SendPropertyChanging();
					this._cat_id = value;
					this.SendPropertyChanged("cat_id");
					this.Oncat_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cat_nombre", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string cat_nombre
		{
			get
			{
				return this._cat_nombre;
			}
			set
			{
				if ((this._cat_nombre != value))
				{
					this.Oncat_nombreChanging(value);
					this.SendPropertyChanging();
					this._cat_nombre = value;
					this.SendPropertyChanged("cat_nombre");
					this.Oncat_nombreChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cat_estado", DbType="Char(1)")]
		public System.Nullable<char> cat_estado
		{
			get
			{
				return this._cat_estado;
			}
			set
			{
				if ((this._cat_estado != value))
				{
					this.Oncat_estadoChanging(value);
					this.SendPropertyChanging();
					this._cat_estado = value;
					this.SendPropertyChanged("cat_estado");
					this.Oncat_estadoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tbl_categoria_tbl_producto", Storage="_tbl_producto", ThisKey="cat_id", OtherKey="cat_id")]
		public EntitySet<tbl_producto> tbl_producto
		{
			get
			{
				return this._tbl_producto;
			}
			set
			{
				this._tbl_producto.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_tbl_producto(tbl_producto entity)
		{
			this.SendPropertyChanging();
			entity.tbl_categoria = this;
		}
		
		private void detach_tbl_producto(tbl_producto entity)
		{
			this.SendPropertyChanging();
			entity.tbl_categoria = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tbl_producto")]
	public partial class tbl_producto : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _pro_id;
		
		private string _pro_nombre;
		
		private int _pro_cantidad;
		
		private decimal _pro_precio;
		
		private System.Nullable<char> _pro_estado;
		
		private System.Nullable<int> _prov_id;
		
		private string _pro_ruta_foto;
		
		private System.Nullable<int> _cat_id;
		
		private System.Nullable<int> _pro_prev_prov_id;
		
		private EntitySet<tbl_carrito> _tbl_carrito;
		
		private EntitySet<tbl_producto_fotos> _tbl_producto_fotos;
		
		private EntityRef<tbl_categoria> _tbl_categoria;
		
		private EntityRef<tbl_proveedor> _tbl_proveedor;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onpro_idChanging(int value);
    partial void Onpro_idChanged();
    partial void Onpro_nombreChanging(string value);
    partial void Onpro_nombreChanged();
    partial void Onpro_cantidadChanging(int value);
    partial void Onpro_cantidadChanged();
    partial void Onpro_precioChanging(decimal value);
    partial void Onpro_precioChanged();
    partial void Onpro_estadoChanging(System.Nullable<char> value);
    partial void Onpro_estadoChanged();
    partial void Onprov_idChanging(System.Nullable<int> value);
    partial void Onprov_idChanged();
    partial void Onpro_ruta_fotoChanging(string value);
    partial void Onpro_ruta_fotoChanged();
    partial void Oncat_idChanging(System.Nullable<int> value);
    partial void Oncat_idChanged();
    partial void Onpro_prev_prov_idChanging(System.Nullable<int> value);
    partial void Onpro_prev_prov_idChanged();
    #endregion
		
		public tbl_producto()
		{
			this._tbl_carrito = new EntitySet<tbl_carrito>(new Action<tbl_carrito>(this.attach_tbl_carrito), new Action<tbl_carrito>(this.detach_tbl_carrito));
			this._tbl_producto_fotos = new EntitySet<tbl_producto_fotos>(new Action<tbl_producto_fotos>(this.attach_tbl_producto_fotos), new Action<tbl_producto_fotos>(this.detach_tbl_producto_fotos));
			this._tbl_categoria = default(EntityRef<tbl_categoria>);
			this._tbl_proveedor = default(EntityRef<tbl_proveedor>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_pro_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int pro_id
		{
			get
			{
				return this._pro_id;
			}
			set
			{
				if ((this._pro_id != value))
				{
					this.Onpro_idChanging(value);
					this.SendPropertyChanging();
					this._pro_id = value;
					this.SendPropertyChanged("pro_id");
					this.Onpro_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_pro_nombre", DbType="VarChar(100) NOT NULL", CanBeNull=false)]
		public string pro_nombre
		{
			get
			{
				return this._pro_nombre;
			}
			set
			{
				if ((this._pro_nombre != value))
				{
					this.Onpro_nombreChanging(value);
					this.SendPropertyChanging();
					this._pro_nombre = value;
					this.SendPropertyChanged("pro_nombre");
					this.Onpro_nombreChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_pro_cantidad", DbType="Int NOT NULL")]
		public int pro_cantidad
		{
			get
			{
				return this._pro_cantidad;
			}
			set
			{
				if ((this._pro_cantidad != value))
				{
					this.Onpro_cantidadChanging(value);
					this.SendPropertyChanging();
					this._pro_cantidad = value;
					this.SendPropertyChanged("pro_cantidad");
					this.Onpro_cantidadChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_pro_precio", DbType="Decimal(18,2) NOT NULL")]
		public decimal pro_precio
		{
			get
			{
				return this._pro_precio;
			}
			set
			{
				if ((this._pro_precio != value))
				{
					this.Onpro_precioChanging(value);
					this.SendPropertyChanging();
					this._pro_precio = value;
					this.SendPropertyChanged("pro_precio");
					this.Onpro_precioChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_pro_estado", DbType="Char(1)")]
		public System.Nullable<char> pro_estado
		{
			get
			{
				return this._pro_estado;
			}
			set
			{
				if ((this._pro_estado != value))
				{
					this.Onpro_estadoChanging(value);
					this.SendPropertyChanging();
					this._pro_estado = value;
					this.SendPropertyChanged("pro_estado");
					this.Onpro_estadoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_prov_id", DbType="Int")]
		public System.Nullable<int> prov_id
		{
			get
			{
				return this._prov_id;
			}
			set
			{
				if ((this._prov_id != value))
				{
					if (this._tbl_proveedor.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onprov_idChanging(value);
					this.SendPropertyChanging();
					this._prov_id = value;
					this.SendPropertyChanged("prov_id");
					this.Onprov_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_pro_ruta_foto", DbType="VarChar(250)")]
		public string pro_ruta_foto
		{
			get
			{
				return this._pro_ruta_foto;
			}
			set
			{
				if ((this._pro_ruta_foto != value))
				{
					this.Onpro_ruta_fotoChanging(value);
					this.SendPropertyChanging();
					this._pro_ruta_foto = value;
					this.SendPropertyChanged("pro_ruta_foto");
					this.Onpro_ruta_fotoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cat_id", DbType="Int")]
		public System.Nullable<int> cat_id
		{
			get
			{
				return this._cat_id;
			}
			set
			{
				if ((this._cat_id != value))
				{
					if (this._tbl_categoria.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Oncat_idChanging(value);
					this.SendPropertyChanging();
					this._cat_id = value;
					this.SendPropertyChanged("cat_id");
					this.Oncat_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_pro_prev_prov_id", DbType="Int")]
		public System.Nullable<int> pro_prev_prov_id
		{
			get
			{
				return this._pro_prev_prov_id;
			}
			set
			{
				if ((this._pro_prev_prov_id != value))
				{
					this.Onpro_prev_prov_idChanging(value);
					this.SendPropertyChanging();
					this._pro_prev_prov_id = value;
					this.SendPropertyChanged("pro_prev_prov_id");
					this.Onpro_prev_prov_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tbl_producto_tbl_carrito", Storage="_tbl_carrito", ThisKey="pro_id", OtherKey="pro_id")]
		public EntitySet<tbl_carrito> tbl_carrito
		{
			get
			{
				return this._tbl_carrito;
			}
			set
			{
				this._tbl_carrito.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tbl_producto_tbl_producto_fotos", Storage="_tbl_producto_fotos", ThisKey="pro_id", OtherKey="pro_id")]
		public EntitySet<tbl_producto_fotos> tbl_producto_fotos
		{
			get
			{
				return this._tbl_producto_fotos;
			}
			set
			{
				this._tbl_producto_fotos.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tbl_categoria_tbl_producto", Storage="_tbl_categoria", ThisKey="cat_id", OtherKey="cat_id", IsForeignKey=true)]
		public tbl_categoria tbl_categoria
		{
			get
			{
				return this._tbl_categoria.Entity;
			}
			set
			{
				tbl_categoria previousValue = this._tbl_categoria.Entity;
				if (((previousValue != value) 
							|| (this._tbl_categoria.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._tbl_categoria.Entity = null;
						previousValue.tbl_producto.Remove(this);
					}
					this._tbl_categoria.Entity = value;
					if ((value != null))
					{
						value.tbl_producto.Add(this);
						this._cat_id = value.cat_id;
					}
					else
					{
						this._cat_id = default(Nullable<int>);
					}
					this.SendPropertyChanged("tbl_categoria");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tbl_proveedor_tbl_producto", Storage="_tbl_proveedor", ThisKey="prov_id", OtherKey="prov_id", IsForeignKey=true)]
		public tbl_proveedor tbl_proveedor
		{
			get
			{
				return this._tbl_proveedor.Entity;
			}
			set
			{
				tbl_proveedor previousValue = this._tbl_proveedor.Entity;
				if (((previousValue != value) 
							|| (this._tbl_proveedor.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._tbl_proveedor.Entity = null;
						previousValue.tbl_producto.Remove(this);
					}
					this._tbl_proveedor.Entity = value;
					if ((value != null))
					{
						value.tbl_producto.Add(this);
						this._prov_id = value.prov_id;
					}
					else
					{
						this._prov_id = default(Nullable<int>);
					}
					this.SendPropertyChanged("tbl_proveedor");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_tbl_carrito(tbl_carrito entity)
		{
			this.SendPropertyChanging();
			entity.tbl_producto = this;
		}
		
		private void detach_tbl_carrito(tbl_carrito entity)
		{
			this.SendPropertyChanging();
			entity.tbl_producto = null;
		}
		
		private void attach_tbl_producto_fotos(tbl_producto_fotos entity)
		{
			this.SendPropertyChanging();
			entity.tbl_producto = this;
		}
		
		private void detach_tbl_producto_fotos(tbl_producto_fotos entity)
		{
			this.SendPropertyChanging();
			entity.tbl_producto = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tbl_producto_fotos")]
	public partial class tbl_producto_fotos : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _pfot_id;
		
		private int _pro_id;
		
		private string _pfot_ruta_foto;
		
		private System.Nullable<System.DateTime> _pfot_fecha;
		
		private EntityRef<tbl_producto> _tbl_producto;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onpfot_idChanging(int value);
    partial void Onpfot_idChanged();
    partial void Onpro_idChanging(int value);
    partial void Onpro_idChanged();
    partial void Onpfot_ruta_fotoChanging(string value);
    partial void Onpfot_ruta_fotoChanged();
    partial void Onpfot_fechaChanging(System.Nullable<System.DateTime> value);
    partial void Onpfot_fechaChanged();
    #endregion
		
		public tbl_producto_fotos()
		{
			this._tbl_producto = default(EntityRef<tbl_producto>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_pfot_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int pfot_id
		{
			get
			{
				return this._pfot_id;
			}
			set
			{
				if ((this._pfot_id != value))
				{
					this.Onpfot_idChanging(value);
					this.SendPropertyChanging();
					this._pfot_id = value;
					this.SendPropertyChanged("pfot_id");
					this.Onpfot_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_pro_id", DbType="Int NOT NULL")]
		public int pro_id
		{
			get
			{
				return this._pro_id;
			}
			set
			{
				if ((this._pro_id != value))
				{
					if (this._tbl_producto.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onpro_idChanging(value);
					this.SendPropertyChanging();
					this._pro_id = value;
					this.SendPropertyChanged("pro_id");
					this.Onpro_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_pfot_ruta_foto", DbType="VarChar(500) NOT NULL", CanBeNull=false)]
		public string pfot_ruta_foto
		{
			get
			{
				return this._pfot_ruta_foto;
			}
			set
			{
				if ((this._pfot_ruta_foto != value))
				{
					this.Onpfot_ruta_fotoChanging(value);
					this.SendPropertyChanging();
					this._pfot_ruta_foto = value;
					this.SendPropertyChanged("pfot_ruta_foto");
					this.Onpfot_ruta_fotoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_pfot_fecha", DbType="DateTime")]
		public System.Nullable<System.DateTime> pfot_fecha
		{
			get
			{
				return this._pfot_fecha;
			}
			set
			{
				if ((this._pfot_fecha != value))
				{
					this.Onpfot_fechaChanging(value);
					this.SendPropertyChanging();
					this._pfot_fecha = value;
					this.SendPropertyChanged("pfot_fecha");
					this.Onpfot_fechaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tbl_producto_tbl_producto_fotos", Storage="_tbl_producto", ThisKey="pro_id", OtherKey="pro_id", IsForeignKey=true)]
		public tbl_producto tbl_producto
		{
			get
			{
				return this._tbl_producto.Entity;
			}
			set
			{
				tbl_producto previousValue = this._tbl_producto.Entity;
				if (((previousValue != value) 
							|| (this._tbl_producto.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._tbl_producto.Entity = null;
						previousValue.tbl_producto_fotos.Remove(this);
					}
					this._tbl_producto.Entity = value;
					if ((value != null))
					{
						value.tbl_producto_fotos.Add(this);
						this._pro_id = value.pro_id;
					}
					else
					{
						this._pro_id = default(int);
					}
					this.SendPropertyChanged("tbl_producto");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tbl_proveedor")]
	public partial class tbl_proveedor : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _prov_id;
		
		private string _prov_nombre;
		
		private System.Nullable<char> _prov_estado;
		
		private EntitySet<tbl_producto> _tbl_producto;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onprov_idChanging(int value);
    partial void Onprov_idChanged();
    partial void Onprov_nombreChanging(string value);
    partial void Onprov_nombreChanged();
    partial void Onprov_estadoChanging(System.Nullable<char> value);
    partial void Onprov_estadoChanged();
    #endregion
		
		public tbl_proveedor()
		{
			this._tbl_producto = new EntitySet<tbl_producto>(new Action<tbl_producto>(this.attach_tbl_producto), new Action<tbl_producto>(this.detach_tbl_producto));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_prov_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int prov_id
		{
			get
			{
				return this._prov_id;
			}
			set
			{
				if ((this._prov_id != value))
				{
					this.Onprov_idChanging(value);
					this.SendPropertyChanging();
					this._prov_id = value;
					this.SendPropertyChanged("prov_id");
					this.Onprov_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_prov_nombre", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string prov_nombre
		{
			get
			{
				return this._prov_nombre;
			}
			set
			{
				if ((this._prov_nombre != value))
				{
					this.Onprov_nombreChanging(value);
					this.SendPropertyChanging();
					this._prov_nombre = value;
					this.SendPropertyChanged("prov_nombre");
					this.Onprov_nombreChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_prov_estado", DbType="Char(1)")]
		public System.Nullable<char> prov_estado
		{
			get
			{
				return this._prov_estado;
			}
			set
			{
				if ((this._prov_estado != value))
				{
					this.Onprov_estadoChanging(value);
					this.SendPropertyChanging();
					this._prov_estado = value;
					this.SendPropertyChanged("prov_estado");
					this.Onprov_estadoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tbl_proveedor_tbl_producto", Storage="_tbl_producto", ThisKey="prov_id", OtherKey="prov_id")]
		public EntitySet<tbl_producto> tbl_producto
		{
			get
			{
				return this._tbl_producto;
			}
			set
			{
				this._tbl_producto.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_tbl_producto(tbl_producto entity)
		{
			this.SendPropertyChanging();
			entity.tbl_proveedor = this;
		}
		
		private void detach_tbl_producto(tbl_producto entity)
		{
			this.SendPropertyChanging();
			entity.tbl_proveedor = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tbl_tipo_usuario")]
	public partial class tbl_tipo_usuario : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _tusu_id;
		
		private string _tusu_nombre;
		
		private System.Nullable<char> _tusu_estado;
		
		private EntitySet<tbl_usuario> _tbl_usuario;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Ontusu_idChanging(int value);
    partial void Ontusu_idChanged();
    partial void Ontusu_nombreChanging(string value);
    partial void Ontusu_nombreChanged();
    partial void Ontusu_estadoChanging(System.Nullable<char> value);
    partial void Ontusu_estadoChanged();
    #endregion
		
		public tbl_tipo_usuario()
		{
			this._tbl_usuario = new EntitySet<tbl_usuario>(new Action<tbl_usuario>(this.attach_tbl_usuario), new Action<tbl_usuario>(this.detach_tbl_usuario));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tusu_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int tusu_id
		{
			get
			{
				return this._tusu_id;
			}
			set
			{
				if ((this._tusu_id != value))
				{
					this.Ontusu_idChanging(value);
					this.SendPropertyChanging();
					this._tusu_id = value;
					this.SendPropertyChanged("tusu_id");
					this.Ontusu_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tusu_nombre", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string tusu_nombre
		{
			get
			{
				return this._tusu_nombre;
			}
			set
			{
				if ((this._tusu_nombre != value))
				{
					this.Ontusu_nombreChanging(value);
					this.SendPropertyChanging();
					this._tusu_nombre = value;
					this.SendPropertyChanged("tusu_nombre");
					this.Ontusu_nombreChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tusu_estado", DbType="Char(1)")]
		public System.Nullable<char> tusu_estado
		{
			get
			{
				return this._tusu_estado;
			}
			set
			{
				if ((this._tusu_estado != value))
				{
					this.Ontusu_estadoChanging(value);
					this.SendPropertyChanging();
					this._tusu_estado = value;
					this.SendPropertyChanged("tusu_estado");
					this.Ontusu_estadoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tbl_tipo_usuario_tbl_usuario", Storage="_tbl_usuario", ThisKey="tusu_id", OtherKey="tusu_id")]
		public EntitySet<tbl_usuario> tbl_usuario
		{
			get
			{
				return this._tbl_usuario;
			}
			set
			{
				this._tbl_usuario.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_tbl_usuario(tbl_usuario entity)
		{
			this.SendPropertyChanging();
			entity.tbl_tipo_usuario = this;
		}
		
		private void detach_tbl_usuario(tbl_usuario entity)
		{
			this.SendPropertyChanging();
			entity.tbl_tipo_usuario = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tbl_usuario")]
	public partial class tbl_usuario : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _usu_id;
		
		private string _usu_cedula;
		
		private string _usu_nombre;
		
		private string _usu_apellidos;
		
		private string _usu_direccion;
		
		private string _usu_celular;
		
		private string _usu_correo;
		
		private System.Nullable<System.DateTime> _usu_fecha_creacion;
		
		private System.Nullable<System.DateTime> _usu_fecha_cumple;
		
		private string _usu_nick;
		
		private System.Data.Linq.Binary _usu_contrasena;
		
		private System.Nullable<int> _usu_intentos;
		
		private string _usu_codigo_OTP;
		
		private string _usu_otp_hash;
		
		private string _usu_google_id;
		
		private string _usu_facebook_id;
		
		private System.Nullable<System.DateTime> _usu_fecha_Ultimo;
		
		private System.Nullable<int> _usu_puntos;
		
		private System.Nullable<char> _usu_estado;
		
		private int _tusu_id;
		
		private EntitySet<tbl_carrito> _tbl_carrito;
		
		private EntitySet<tbl_usuario_fotos> _tbl_usuario_fotos;
		
		private EntityRef<tbl_tipo_usuario> _tbl_tipo_usuario;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onusu_idChanging(int value);
    partial void Onusu_idChanged();
    partial void Onusu_cedulaChanging(string value);
    partial void Onusu_cedulaChanged();
    partial void Onusu_nombreChanging(string value);
    partial void Onusu_nombreChanged();
    partial void Onusu_apellidosChanging(string value);
    partial void Onusu_apellidosChanged();
    partial void Onusu_direccionChanging(string value);
    partial void Onusu_direccionChanged();
    partial void Onusu_celularChanging(string value);
    partial void Onusu_celularChanged();
    partial void Onusu_correoChanging(string value);
    partial void Onusu_correoChanged();
    partial void Onusu_fecha_creacionChanging(System.Nullable<System.DateTime> value);
    partial void Onusu_fecha_creacionChanged();
    partial void Onusu_fecha_cumpleChanging(System.Nullable<System.DateTime> value);
    partial void Onusu_fecha_cumpleChanged();
    partial void Onusu_nickChanging(string value);
    partial void Onusu_nickChanged();
    partial void Onusu_contrasenaChanging(System.Data.Linq.Binary value);
    partial void Onusu_contrasenaChanged();
    partial void Onusu_intentosChanging(System.Nullable<int> value);
    partial void Onusu_intentosChanged();
    partial void Onusu_codigo_OTPChanging(string value);
    partial void Onusu_codigo_OTPChanged();
    partial void Onusu_otp_hashChanging(string value);
    partial void Onusu_otp_hashChanged();
    partial void Onusu_google_idChanging(string value);
    partial void Onusu_google_idChanged();
    partial void Onusu_facebook_idChanging(string value);
    partial void Onusu_facebook_idChanged();
    partial void Onusu_fecha_UltimoChanging(System.Nullable<System.DateTime> value);
    partial void Onusu_fecha_UltimoChanged();
    partial void Onusu_puntosChanging(System.Nullable<int> value);
    partial void Onusu_puntosChanged();
    partial void Onusu_estadoChanging(System.Nullable<char> value);
    partial void Onusu_estadoChanged();
    partial void Ontusu_idChanging(int value);
    partial void Ontusu_idChanged();
    #endregion
		
		public tbl_usuario()
		{
			this._tbl_carrito = new EntitySet<tbl_carrito>(new Action<tbl_carrito>(this.attach_tbl_carrito), new Action<tbl_carrito>(this.detach_tbl_carrito));
			this._tbl_usuario_fotos = new EntitySet<tbl_usuario_fotos>(new Action<tbl_usuario_fotos>(this.attach_tbl_usuario_fotos), new Action<tbl_usuario_fotos>(this.detach_tbl_usuario_fotos));
			this._tbl_tipo_usuario = default(EntityRef<tbl_tipo_usuario>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_usu_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int usu_id
		{
			get
			{
				return this._usu_id;
			}
			set
			{
				if ((this._usu_id != value))
				{
					this.Onusu_idChanging(value);
					this.SendPropertyChanging();
					this._usu_id = value;
					this.SendPropertyChanged("usu_id");
					this.Onusu_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_usu_cedula", DbType="VarChar(10)")]
		public string usu_cedula
		{
			get
			{
				return this._usu_cedula;
			}
			set
			{
				if ((this._usu_cedula != value))
				{
					this.Onusu_cedulaChanging(value);
					this.SendPropertyChanging();
					this._usu_cedula = value;
					this.SendPropertyChanged("usu_cedula");
					this.Onusu_cedulaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_usu_nombre", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string usu_nombre
		{
			get
			{
				return this._usu_nombre;
			}
			set
			{
				if ((this._usu_nombre != value))
				{
					this.Onusu_nombreChanging(value);
					this.SendPropertyChanging();
					this._usu_nombre = value;
					this.SendPropertyChanged("usu_nombre");
					this.Onusu_nombreChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_usu_apellidos", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string usu_apellidos
		{
			get
			{
				return this._usu_apellidos;
			}
			set
			{
				if ((this._usu_apellidos != value))
				{
					this.Onusu_apellidosChanging(value);
					this.SendPropertyChanging();
					this._usu_apellidos = value;
					this.SendPropertyChanged("usu_apellidos");
					this.Onusu_apellidosChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_usu_direccion", DbType="VarChar(250)")]
		public string usu_direccion
		{
			get
			{
				return this._usu_direccion;
			}
			set
			{
				if ((this._usu_direccion != value))
				{
					this.Onusu_direccionChanging(value);
					this.SendPropertyChanging();
					this._usu_direccion = value;
					this.SendPropertyChanged("usu_direccion");
					this.Onusu_direccionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_usu_celular", DbType="VarChar(15)")]
		public string usu_celular
		{
			get
			{
				return this._usu_celular;
			}
			set
			{
				if ((this._usu_celular != value))
				{
					this.Onusu_celularChanging(value);
					this.SendPropertyChanging();
					this._usu_celular = value;
					this.SendPropertyChanged("usu_celular");
					this.Onusu_celularChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_usu_correo", DbType="VarChar(150) NOT NULL", CanBeNull=false)]
		public string usu_correo
		{
			get
			{
				return this._usu_correo;
			}
			set
			{
				if ((this._usu_correo != value))
				{
					this.Onusu_correoChanging(value);
					this.SendPropertyChanging();
					this._usu_correo = value;
					this.SendPropertyChanged("usu_correo");
					this.Onusu_correoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_usu_fecha_creacion", DbType="DateTime")]
		public System.Nullable<System.DateTime> usu_fecha_creacion
		{
			get
			{
				return this._usu_fecha_creacion;
			}
			set
			{
				if ((this._usu_fecha_creacion != value))
				{
					this.Onusu_fecha_creacionChanging(value);
					this.SendPropertyChanging();
					this._usu_fecha_creacion = value;
					this.SendPropertyChanged("usu_fecha_creacion");
					this.Onusu_fecha_creacionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_usu_fecha_cumple", DbType="Date")]
		public System.Nullable<System.DateTime> usu_fecha_cumple
		{
			get
			{
				return this._usu_fecha_cumple;
			}
			set
			{
				if ((this._usu_fecha_cumple != value))
				{
					this.Onusu_fecha_cumpleChanging(value);
					this.SendPropertyChanging();
					this._usu_fecha_cumple = value;
					this.SendPropertyChanged("usu_fecha_cumple");
					this.Onusu_fecha_cumpleChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_usu_nick", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string usu_nick
		{
			get
			{
				return this._usu_nick;
			}
			set
			{
				if ((this._usu_nick != value))
				{
					this.Onusu_nickChanging(value);
					this.SendPropertyChanging();
					this._usu_nick = value;
					this.SendPropertyChanged("usu_nick");
					this.Onusu_nickChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_usu_contrasena", DbType="VarBinary(MAX) NOT NULL", CanBeNull=false, UpdateCheck=UpdateCheck.Never)]
		public System.Data.Linq.Binary usu_contrasena
		{
			get
			{
				return this._usu_contrasena;
			}
			set
			{
				if ((this._usu_contrasena != value))
				{
					this.Onusu_contrasenaChanging(value);
					this.SendPropertyChanging();
					this._usu_contrasena = value;
					this.SendPropertyChanged("usu_contrasena");
					this.Onusu_contrasenaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_usu_intentos", DbType="Int")]
		public System.Nullable<int> usu_intentos
		{
			get
			{
				return this._usu_intentos;
			}
			set
			{
				if ((this._usu_intentos != value))
				{
					this.Onusu_intentosChanging(value);
					this.SendPropertyChanging();
					this._usu_intentos = value;
					this.SendPropertyChanged("usu_intentos");
					this.Onusu_intentosChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_usu_codigo_OTP", DbType="VarChar(100)")]
		public string usu_codigo_OTP
		{
			get
			{
				return this._usu_codigo_OTP;
			}
			set
			{
				if ((this._usu_codigo_OTP != value))
				{
					this.Onusu_codigo_OTPChanging(value);
					this.SendPropertyChanging();
					this._usu_codigo_OTP = value;
					this.SendPropertyChanged("usu_codigo_OTP");
					this.Onusu_codigo_OTPChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_usu_otp_hash", DbType="VarChar(500)")]
		public string usu_otp_hash
		{
			get
			{
				return this._usu_otp_hash;
			}
			set
			{
				if ((this._usu_otp_hash != value))
				{
					this.Onusu_otp_hashChanging(value);
					this.SendPropertyChanging();
					this._usu_otp_hash = value;
					this.SendPropertyChanged("usu_otp_hash");
					this.Onusu_otp_hashChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_usu_google_id", DbType="VarChar(100)")]
		public string usu_google_id
		{
			get
			{
				return this._usu_google_id;
			}
			set
			{
				if ((this._usu_google_id != value))
				{
					this.Onusu_google_idChanging(value);
					this.SendPropertyChanging();
					this._usu_google_id = value;
					this.SendPropertyChanged("usu_google_id");
					this.Onusu_google_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_usu_facebook_id", DbType="VarChar(100)")]
		public string usu_facebook_id
		{
			get
			{
				return this._usu_facebook_id;
			}
			set
			{
				if ((this._usu_facebook_id != value))
				{
					this.Onusu_facebook_idChanging(value);
					this.SendPropertyChanging();
					this._usu_facebook_id = value;
					this.SendPropertyChanged("usu_facebook_id");
					this.Onusu_facebook_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_usu_fecha_Ultimo", DbType="DateTime")]
		public System.Nullable<System.DateTime> usu_fecha_Ultimo
		{
			get
			{
				return this._usu_fecha_Ultimo;
			}
			set
			{
				if ((this._usu_fecha_Ultimo != value))
				{
					this.Onusu_fecha_UltimoChanging(value);
					this.SendPropertyChanging();
					this._usu_fecha_Ultimo = value;
					this.SendPropertyChanged("usu_fecha_Ultimo");
					this.Onusu_fecha_UltimoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_usu_puntos", DbType="Int")]
		public System.Nullable<int> usu_puntos
		{
			get
			{
				return this._usu_puntos;
			}
			set
			{
				if ((this._usu_puntos != value))
				{
					this.Onusu_puntosChanging(value);
					this.SendPropertyChanging();
					this._usu_puntos = value;
					this.SendPropertyChanged("usu_puntos");
					this.Onusu_puntosChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_usu_estado", DbType="Char(1)")]
		public System.Nullable<char> usu_estado
		{
			get
			{
				return this._usu_estado;
			}
			set
			{
				if ((this._usu_estado != value))
				{
					this.Onusu_estadoChanging(value);
					this.SendPropertyChanging();
					this._usu_estado = value;
					this.SendPropertyChanged("usu_estado");
					this.Onusu_estadoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tusu_id", DbType="Int NOT NULL")]
		public int tusu_id
		{
			get
			{
				return this._tusu_id;
			}
			set
			{
				if ((this._tusu_id != value))
				{
					if (this._tbl_tipo_usuario.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Ontusu_idChanging(value);
					this.SendPropertyChanging();
					this._tusu_id = value;
					this.SendPropertyChanged("tusu_id");
					this.Ontusu_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tbl_usuario_tbl_carrito", Storage="_tbl_carrito", ThisKey="usu_id", OtherKey="usu_id")]
		public EntitySet<tbl_carrito> tbl_carrito
		{
			get
			{
				return this._tbl_carrito;
			}
			set
			{
				this._tbl_carrito.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tbl_usuario_tbl_usuario_fotos", Storage="_tbl_usuario_fotos", ThisKey="usu_id", OtherKey="usu_id")]
		public EntitySet<tbl_usuario_fotos> tbl_usuario_fotos
		{
			get
			{
				return this._tbl_usuario_fotos;
			}
			set
			{
				this._tbl_usuario_fotos.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tbl_tipo_usuario_tbl_usuario", Storage="_tbl_tipo_usuario", ThisKey="tusu_id", OtherKey="tusu_id", IsForeignKey=true)]
		public tbl_tipo_usuario tbl_tipo_usuario
		{
			get
			{
				return this._tbl_tipo_usuario.Entity;
			}
			set
			{
				tbl_tipo_usuario previousValue = this._tbl_tipo_usuario.Entity;
				if (((previousValue != value) 
							|| (this._tbl_tipo_usuario.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._tbl_tipo_usuario.Entity = null;
						previousValue.tbl_usuario.Remove(this);
					}
					this._tbl_tipo_usuario.Entity = value;
					if ((value != null))
					{
						value.tbl_usuario.Add(this);
						this._tusu_id = value.tusu_id;
					}
					else
					{
						this._tusu_id = default(int);
					}
					this.SendPropertyChanged("tbl_tipo_usuario");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_tbl_carrito(tbl_carrito entity)
		{
			this.SendPropertyChanging();
			entity.tbl_usuario = this;
		}
		
		private void detach_tbl_carrito(tbl_carrito entity)
		{
			this.SendPropertyChanging();
			entity.tbl_usuario = null;
		}
		
		private void attach_tbl_usuario_fotos(tbl_usuario_fotos entity)
		{
			this.SendPropertyChanging();
			entity.tbl_usuario = this;
		}
		
		private void detach_tbl_usuario_fotos(tbl_usuario_fotos entity)
		{
			this.SendPropertyChanging();
			entity.tbl_usuario = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tbl_usuario_fotos")]
	public partial class tbl_usuario_fotos : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _foto_id;
		
		private int _usu_id;
		
		private System.Data.Linq.Binary _foto_data;
		
		private System.Nullable<System.DateTime> _foto_fecha;
		
		private EntityRef<tbl_usuario> _tbl_usuario;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onfoto_idChanging(int value);
    partial void Onfoto_idChanged();
    partial void Onusu_idChanging(int value);
    partial void Onusu_idChanged();
    partial void Onfoto_dataChanging(System.Data.Linq.Binary value);
    partial void Onfoto_dataChanged();
    partial void Onfoto_fechaChanging(System.Nullable<System.DateTime> value);
    partial void Onfoto_fechaChanged();
    #endregion
		
		public tbl_usuario_fotos()
		{
			this._tbl_usuario = default(EntityRef<tbl_usuario>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_foto_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int foto_id
		{
			get
			{
				return this._foto_id;
			}
			set
			{
				if ((this._foto_id != value))
				{
					this.Onfoto_idChanging(value);
					this.SendPropertyChanging();
					this._foto_id = value;
					this.SendPropertyChanged("foto_id");
					this.Onfoto_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_usu_id", DbType="Int NOT NULL")]
		public int usu_id
		{
			get
			{
				return this._usu_id;
			}
			set
			{
				if ((this._usu_id != value))
				{
					if (this._tbl_usuario.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onusu_idChanging(value);
					this.SendPropertyChanging();
					this._usu_id = value;
					this.SendPropertyChanged("usu_id");
					this.Onusu_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_foto_data", DbType="VarBinary(MAX) NOT NULL", CanBeNull=false, UpdateCheck=UpdateCheck.Never)]
		public System.Data.Linq.Binary foto_data
		{
			get
			{
				return this._foto_data;
			}
			set
			{
				if ((this._foto_data != value))
				{
					this.Onfoto_dataChanging(value);
					this.SendPropertyChanging();
					this._foto_data = value;
					this.SendPropertyChanged("foto_data");
					this.Onfoto_dataChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_foto_fecha", DbType="DateTime")]
		public System.Nullable<System.DateTime> foto_fecha
		{
			get
			{
				return this._foto_fecha;
			}
			set
			{
				if ((this._foto_fecha != value))
				{
					this.Onfoto_fechaChanging(value);
					this.SendPropertyChanging();
					this._foto_fecha = value;
					this.SendPropertyChanged("foto_fecha");
					this.Onfoto_fechaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tbl_usuario_tbl_usuario_fotos", Storage="_tbl_usuario", ThisKey="usu_id", OtherKey="usu_id", IsForeignKey=true)]
		public tbl_usuario tbl_usuario
		{
			get
			{
				return this._tbl_usuario.Entity;
			}
			set
			{
				tbl_usuario previousValue = this._tbl_usuario.Entity;
				if (((previousValue != value) 
							|| (this._tbl_usuario.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._tbl_usuario.Entity = null;
						previousValue.tbl_usuario_fotos.Remove(this);
					}
					this._tbl_usuario.Entity = value;
					if ((value != null))
					{
						value.tbl_usuario_fotos.Add(this);
						this._usu_id = value.usu_id;
					}
					else
					{
						this._usu_id = default(int);
					}
					this.SendPropertyChanged("tbl_usuario");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
